apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  labels:
    app: ${NAME}
    name: ${NAME}
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${NAME}
    stringData:
      db_password: "${ADMIN_DB_PASSWORD}"
      db_username: "${ADMIN_DB_USERNAME}"
      db_name: "${BPM_DATABASE_NAME}"
      camunda_jdbc_url: "jdbc:postgresql://${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${BPM_DATABASE_NAME}?user=${ADMIN_DB_USERNAME}"
      wait_for: "${DATABASE_SERVICE_NAME}:${DATABASE_PORT}"
      keycloak_url: "${KEYCLOAK_URL}"
      keycloak_clientid: "${keycloak_clientid}"
      keycloak_clientsecret: "${keycloak_clientsecret}"
      keycloak_realm: "${keycloak_realm}"
      formio_root_email: "${FORMIO_ROOT_EMAIL}"
      formio_root_password: "${FORMIO_ROOT_PASSWORD}"
      BPM_API_BASE: "${BPM_API_BASE}/camunda"
      BPM_CLIENT_ID: "${FFA_BPM_KEYCLOAK_CLIENTID}"
      BPM_CLIENT_SECRET: "${FFA_BPM_KEYCLOAK_CLIENTSECRET}"
      BPM_TOKEN_API: ""
      JWT_OIDC_ALGORITHMS: RS256
      JWT_OIDC_AUDIENCE: forms-flow-web
      JWT_OIDC_CACHING_ENABLED: "True"
      JWT_OIDC_ISSUER: "${KEYCLOAK_URL}/auth/realms/${keycloak_realm}"
      JWT_OIDC_JWKS_CACHE_TIMEOUT: "300"
      JWT_OIDC_JWKS_URI: "${KEYCLOAK_URL}/auth/realms/${keycloak_realm}/protocol/openid-connect/certs"
      JWT_OIDC_WELL_KNOWN_CONFIG: "${KEYCLOAK_URL}/auth/realms/${keycloak_realm}/.well-known/openid-configuration"
      WEB_API_BASE_URL: "${WEB_API_BASE_URL}"
      FORMS_API_BASE_URL: "${FORMS_API_BASE_URL}"
      DEBUG: formio:*
      MONGODB_URI: "${MONGODB_URI}"
      NODE_CONFIG: '{"mongo": "${MONGODB_URI}"}'
      DATABASE_URL: "postgresql://${ADMIN_DB_USERNAME}:${ADMIN_DB_PASSWORD}@${DATABASE_SERVICE_NAME}:${DATABASE_PORT}/${API_DATABASE_NAME}"

    type: Opaque

parameters:
  - name: NAME
    description: The name for all created objects.
    required: true
    value: forms-flow-ai
  - name: FORMIO_ROOT_EMAIL
    description: FORMIO_ROOT_EMAIL
    required: true
  - name: FORMIO_ROOT_PASSWORD
    description: FORMIO_ROOT_PASSWORD
    generate: expression
    from: "[a-zA-Z0-9]{16}"
  - name: ADMIN_DB_USERNAME
    displayName: ADMIN_DB_USERNAME
    description: ADMIN_DB_USERNAME
    required: true
  - name: ADMIN_DB_PASSWORD
    displayName: ADMIN_DB_PASSWORD
    description: ADMIN_DB_PASSWORD
    required: true
  - name: keycloak_clientid
    displayName: keycloak_clientid
    description: keycloak_clientid
    required: true
  - name: keycloak_clientsecret
    displayName: keycloak_clientsecret
    description: keycloak_clientsecret
    required: true
  - name: KEYCLOAK_URL
    displayName: KEYCLOAK_URL
    description: KEYCLOAK_URL
    required: true
  - name: keycloak_realm
    displayName: keycloak_realm
    description: keycloak_realm
    required: true
  - name: FFA_BPM_KEYCLOAK_CLIENTSECRET
    description: FFA_BPM_KEYCLOAK_CLIENTSECRET
    required: true
  - name: FFA_BPM_KEYCLOAK_CLIENTID
    description: FFA_BPM_KEYCLOAK_CLIENTID
    required: true
  - name: WEB_API_BASE_URL
    description: WEB_API_BASE_URL
    required: true
  - name: FORMS_API_BASE_URL
    description: FORMS_API_BASE_URL
    required: true
  - name: DATABASE_SERVICE_NAME
    description: DATABASE_SERVICE_NAME
    required: true
  - name: DATABASE_PORT
    description: DATABASE_PORT
    required: true
  - name: API_DATABASE_NAME
    description: API_DATABASE_NAME
    required: true
  - name: BPM_DATABASE_NAME
    description: BPM_DATABASE_NAME
    required: true
  - name: MONGODB_URI
    description: MONGODB_URI
    required: true
  - name: BPM_API_BASE
    description: BPM_API_BASE
    required: true
